# Site settings
title: Jacek Nakonieczny
email: jacek.nakonieczny@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Yet Another Developer's Blog. Place to drop toughts and notes about work, personal projects and other stuff.
baseurl: "" # the subpath of your site, e.g. /blog/
permalink: /posts/:title
url: "http://blog.nakonieczny.it" # the base hostname & protocol for your site
paginate: 5
paginate_path: /page/:num/

twitter_username: vircung
github_username: vircung
flickr_username: vircung
linkedin_username: jaceknakonieczny
gplus_username: JacekNakonieczny

# Build settings
markdown: kramdown
excerpt_separator: <!-- more -->
