# Site settings
title: Jacek "vircung" Nakonieczny
email: jacek.nakonieczny+vircung@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Quality content of my own.
baseurl: "" # the subpath of your site, e.g. /blog/
permalink: /posts/:title
url: "http://www.vircung.com" # the base hostname & protocol for your site
paginate: 5
paginate_path: /page/:num/

twitter_username: vircung
github_username: vircung
flickr_username: vircung

# Build settings
markdown: kramdown
excerpt_separator: <!-- more -->
